#!/bin/bash

VERSION=${VERSION:-$(pwd)/kernel}

DISTRIBUTION=${DISTRIBUTION:-$(cat /etc/sl*n)}
KERNELVERSION=${KERNELVERSION:-$(cat /proc/version|awk '{print $1" "$3}')}
USER_HOST=${USER_HOST:-$(cat /proc/version| cut -c23-49)}
DATETIME=${DATETIME:-$(cat /proc/version|cut -c83-110)}
COMPILER=${COMPILER:-$(cat /proc/version|cut -c52-69)}


HELLO="\n       \e[1;33mShell Script Usando Include ..!!!
       
       \e[1;35mHello World \e[1;36m${USER}\e[1;35m, eu sou o \e[1;36m${OSTYPE}
       \e[1;35mDistribution\e[1;36m: \e[1;31m${DISTRIBUTION}
       \e[1;35mKernel Version\e[1;36m: \e[1;31m${KERNELVERSION}
       \e[1;35mCompilada por\e[1;36m: \e[1;31m${USER_HOST}
       \e[1;35mCompilada dia\e[1;36m: \e[1;31m${DATETIME}
       \e[1;35mCompilador usado\e[1;36m: \e[1;31m${COMPILER}  
      "