#!/bin/sh

PROFILE=/etc/profile
LILO=/etc/lilo.conf
SUDOERS=/etc/sudoers
MODULESLOCAL=/etc/rc.d/rc.modules.local
SHAREKEYBOARDEVDEV=/usr/share/X11/xorg.conf.d/90-keyboard-layout-evdev.conf
SHAREKEYBOARD=/usr/share/X11/xorg.conf.d/90-keyboard-layout.conf
KEYBOARD=/etc/X11/xorg.conf.d/90-keyboard-layout.conf

KVERSION=$(ls -t /lib/modules | grep -m 1 4.9.44 | sed 's\/\\g';)
DISK=$(mount | grep /dev/sda | awk  '{print $1}')
PART=$(mount | grep /dev/sda | awk  '{print $1}' | sed 's/\/dev\/sda/sda/g')
SDA=$(mount | grep /dev/sda | awk  '{print $1}' | sed 's/\/dev\/.*/\/dev\/sda/g;')
SYSARQ=$(file -s $DISK | awk '{print $5}')
GENERIC=/boot/vmlinuz-generic
INITRDZRAM=/boot/initrd-$(uname -r)-zram
ZRAMINITRD=/boot/initrd-zram
VER=$(cat /etc/slackware-version)

groupadd sudo
groupadd tar

rm -rf /etc/inittab
rm -rf /etc/rc.d/rc.{4,M,S}
rm -rf /etc/profile.d/lang.{csh,sh}

cp sys/{inittab,sysctl.conf} /etc
cp sys/lang.{csh,sh} /etc/profile.d/
cp sys/rc.{4,M,S,zram} /etc/rc.d

if [ -f $SHAREKEYBOARDEVDEV ]; then

cp $SHAREKEYBOARDEVDEV  $KEYBOARD

elif [ -f $SHAREKEYBOARD ]; then

cp $SHAREKEYBOARD $KEYBOARD

fi

# Substitui @ por ponto na linha 57
sed -i '57s/@/./g;' $PROFILE

# Substitui us por br
sed -i '/"us"/ s/"us"/"br"/g;' $KEYBOARD

# Substitui aspas vazias por abnt2
sed -i '/""/ s/""/"abnt2"/g;' $KEYBOARD

# Descomenta Option
sed -i '/#Option/ s/^#//g;' $KEYBOARD

# Descomenta compact
sed -i 's/^#compact/compact/g;' $LILO

# Modifica timeout padrao para 5s
sed -i 's/^timeout =.*/timeout = 50/g;' $LILO

# Modifica label padrao para  SLCKWRLNX
sed -i 's/^  label =.*/  label = SLCKWRLNX/g;' $LILO

# Adiciona suport UTF8 para a partição corrent
sed -i '6s/append=.*/append="\/dev\/'$PART' vt.default_utf8=1"/g;' $LILO

# Retira quebra de linha da linha 8
sed -i 'N;8s/\n//g;' $LILO

# Adiciona quebra de linha na linha 7
sed -i '7s/boot = \/dev\/sda/boot = \/dev\/'$SDA'\n/g;' $LILO

sed -i '/root/ s/ALL=(/ALL=(ALL:/g;' $SUDOERS
sed -i '/%sudo/ s/^#//g;/%sudo/ s/^ //g;/%sudo/ s/ALL=(/ALL=(ALL:/g;' $SUDOERS

if [ -f $MODULESLOCAL ]; then
 echo "/sbin/modprobe zram" >> $MODULESLOCAL
fi

chmod 755 -v /etc/rc.d/rc.zram
   /sbin/nmtui
   #. /etc/rc.d/rc.zram start
   #. /etc/rc.d/rc.mysqld start
   #. /etc/rc.d/rc.networkmanager start
   
if [ -f /etc/slackware-version ]; then



echo "Welcome to $VER \s-\r.\m \l" > /etc/issue

fi

installpkg python/wxPython-2.8.12.1-x86_64-5_slonly.txz
installpkg python/python3-3.6.0-x86_64-3_SBo.tgz
installpkg python/python3-3.5.1-x86_64-1_slack.txz
installpkg python/python-django-tagging-0.4.3-x86_64-1_slonly.txz
installpkg python/python-django-1.10-x86_64-1_slonly.txz
installpkg vlc/flash-player-npapi-26.0.0.151-release.x86_64.tgz
installpkg vlc/npapi-vlc-20170523-x86_64-1alien.txz
installpkg vlc/vlc-2.2.6-x86_64-1alien.txz
installpkg navegadores/mozilla-firefox-56.0b2-x86_64-1.txz
installpkg navegadores/tor-browser-7.0.4-x86_64-1_SBo.tgz

read -p "Crie um usuario: " usuario

echo -e "\n\t\e[1;31mAdicionando\e[0m $usuario\n"

useradd -m $usuario

passwd $usuario

mkdir -p /home/$usuario/{Documentos,Downloads,Imagens,Musicas,Videos,Filmes,Packages,Projetos,Workspace}

touch /home/$usuario/.{bashrc,profile}

chown -R $usuario.$usuario /home/$usuario

usermod -aG sudo,tar,users,floppy,audio,video,cdrom,plugdev,power,netdev,lp,scanner $usuario 

echo "
if [ -f \"/etc/profile\" ]; then
  . \"/etc/profile\"
fi
     " >> /home/$usuario/.bashrc
        
#echo "     
#if [ -f \"$HOME/.bashrc\" ]; then 
#  . \"$HOME/.bashrc\"
#fi
#     " >> /home/$usuario/.profile

touch /root/.{bashrc,profile}


echo "
if [ -f \"/etc/profile\" ]; then
  . \"/etc/profile\"
fi
     " >> /root/.bashrc
      
#echo "     
#if [ -f \"$HOME/.bashrc\" ]; then 
#  . \"$HOME/.bashrc\"
#fi
#     " >> /root/.profile
    
echo -e "\n\t\e[0m$usuario \e[1;31mAdicionado com sucesso..\n\e[0m"


#mkinitrd -c -k $(uname -r) -f $SYSARQ -r $DISK -m mbcache:jbd2:$SYSARQ -u -o $INITRDZRAM

#mkinitrd -c -k $(uname -r) -f $SYSARQ -r $DISK -m usb-storage:xhci-hcd:uas:xhci-pci:ohci-pci:ehci-pci:uhci-hcd:ehci-hcd:hid:usbhid:i2c-hid:hid_generic:hid-cherry:hid-logitech:hid-logitech-dj:hid-logitech-hidpp:hid-lenovo:hid-microsoft:hid_multitouch:mbcache:jbd2:$SYSARQ -u -o $INITRDZRAM

#mkinitrd -c -k $KVERSION -f $SYSARQ -r $DISK -m usb-storage:xhci-hcd:uas:xhci-pci:ohci-pci:ehci-pci:uhci-hcd:ehci-hcd:hid:usbhid:i2c-hid:hid_generic:hid-cherry:hid-logitech:hid-logitech-dj:hid-logitech-hidpp:hid-lenovo:hid-microsoft:hid_multitouch:mbcache:jbd2:$SYSARQ -u -o $INITRDZRAM

ln -s $INITRDZRAM $ZRAMINITRD

## Adiciona partição após "# End LILO global section"

sed -i '/# End LILO global section/a # Linux bootable generic partition config begins' $LILO
sed -i '/# Linux bootable generic partition config begins/a image = '$GENERIC'' $LILO
sed -i '/^image = \/boot\/vmlinuz-generic/a initrd = '$ZRAMINITRD'' $LILO
sed -i '/^initrd = \/boot\/initrd-zram/a root = '$DISK'' $LILO
sed -i '/^root = \/dev\/'$PART'/a label = GNRCLNX' $LILO
sed -i '/^label = GNRCLNX/a read-only' $LILO
sed -i '/^read-only/a # Linux bootable generic partition config ends' $LILO


## Adiciona partição no fim de lilo.conf
#echo "# Linux bootable generic partition config begins" >> $LILO
#echo "image = $GENERIC" >> $LILO
#echo "initrd = $ZRAMINITRD" >> $LILO 
#echo "  root = $DISK" >> $LILO
#echo "  label = GNRCLNX" >> $LILO
#echo "  read-only " >> $LILO
#echo "# Linux bootable generic partition config ends" >> $LILO

lilo
