#!/bin/bash -x
ou
#!/bin/bash -vx
Onde:

    v :: Mostra os comandos à medida que são lidos pelo bash.
    
    x :: Expande os resultados dos comandos e variáveis
    (muito útil quando o shell script possui variáveis numéricas e laços de repetição, por exemplo).
    
Caso nao queira usar um dos comandos acima em seu arquivo shell
basta fazer:

bash-4.4 bash -x meuscript.sh