#!/bin/bash

#altertime=sex_16_mar_2018_21:25:17
altertime=$(date "+%a_%d_%b_%Y_%H:%M:%S")

INITMAKE=${INITMAKE:-~/Workspace/GitHub/shell-script/editmake/initmake}

cd ~/Workspace/GitHub/standard-cxx

find {Aggregation/*,Composition/*,Cadastros/*,DataStructure/*,libmenu/*,Overload/*,Override/*,Polymorphism/*,Regex/*,StringSet/*,TermPaper/*} -name "Makefile" > locates

busca=${busca:-$(find . -name "locates")}

qtd=${qtd:-$(cat ${busca} | wc -l)}

NOMES=($(awk -F'-' '{printf "%s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36}' ${busca}))


for ((l = 0; l < ${qtd}; l++))
do
  
  EDIT=$(echo ${NOMES[${l}]} | sed 's/M/m/g;')
  
  echo "Nome ${l}: ${NOMES[${l}]} Renamed: ${EDIT[0]}"
  
  mv ${NOMES[$l]} ${EDIT[0]}; cat ${INITMAKE} > ${NOMES[${l}]}; cat ${EDIT[0]} >> ${NOMES[${l}]}; rm -rf ${EDIT[0]}
  
  sed -i '/DateTime/ s/:.*/':\ ${altertime}'/g;/DateTime/ s/_/ /g;' ${NOMES[${l}]}
  
  if [ $? -ne 0 ]; then
   echo -e "\e[37;1m\n\t${NOMES[${l}]} \e[m<-\e[31;1m nothing done.!!\e[m\n\n"
  else
   echo -e "\e[36;1m\n\tNome \e[35;1m${l}: \e[m${NOMES[${l}]}\e[31;1m\n\n\tEdited\e[35;1m: \e[33;1m${NOMES[${l}]}\e[m successfully\n\n"
  fi
  
  rm -rf ${busca}
  
done #fim primeiro for