#!/bin/sh
 
PORT=("137" "138" "139" "445" "22" "80" "443")

echo "Bloqueando a porta ${PORT[@]}"
echo -e "\nExemplo de regras para firewall\n"
for porta in ${PORT[@]}
do
echo "Bloqueando a porta ${porta}"

#iptables -A INPUT -p udp --dport ${porta} -j DROP
#iptables -A INPUT -p tcp --dport ${porta} -j DROP
echo ""
done
echo ""