#!/bin/bash
# Programa para baixar ultima versao do firefox utilizando
# o esquema de URL https://download-installer.cdn.mozilla.net/pub/firefox/releases/latest/README.txt
# uso: sh beta [SISTEMA_OPERACIONAL] [LINGUAGEM]
#      Valores default para SISTEMA_OPERACIONAL E LINGUAGEM sao win e pt-BR, respectivamente
#
# exemplo 1: baixar versao para linux 64 bits em ingles:
#            $ sh beta linux64 en-US
# exemplo 2: baixar versao para linux-x86 bits em ingles:
#            $ sh beta linux en-US
# exemplo 3: baixar versao para windows em portugues (valores padrao)
#            $ sh beta
#
### VARIAVEIS
os=$1
linguagem=$2

if [ -z "${ARCH}" ]; then
 case $(uname -m) in
  x86_64) ARCH=64;;  #Downloads for arch x86_64
   i?86|x86) ARCH=""; #Downloads for arch x86
    esac
     fi
### PRINCIPAL
# popular variaveis com valores padrao de sistema operacional e 
# linguagem, caso argumentos nao tenham sido passados 
if [ -z "${os}" ]; then
 case $(uname -s) in
  Linux)
   os=linux${ARCH}
    linguagem=${linguagem:-$(locale | grep "^LC_ALL" |cut -f2 -d = | cut -f1 -d. | sed 's/_/-/g')}
     ;;
  *)
   os=win; #Downloads for arch x86
    linguagem=pt-BR
     esac
fi

#https://download.mozilla.org/?product=firefox-beta-latest&os=linux64&lang=en-US
echo "https://download.mozilla.org/?product=firefox-beta-latest&os=${os}&lang=${linguagem}"

if [ $os = linux${ARCH} ]; then
wget -O firefox_${os}_${linguagem}.tar.bz2 "https://download.mozilla.org/?product=firefox-beta-latest&os=${os}&lang=${linguagem}"
else
wget -O Firefox_${os}_${linguagem}.exe "https://download.mozilla.org/?product=firefox-beta-latest&os=${os}&lang=${linguagem}"
fi

#https://download-installer.cdn.mozilla.net/pub/firefox/releases/60.0b6/linux-x86_64/en-US/firefox-60.0b6.tar.bz2
#https://download-installer.cdn.mozilla.net/pub/firefox/releases/60.0b6/linux-i686/en-US/firefox-60.0b6.tar.bz2