#!/bin/bash
# Programa para baixar ultima versao do firefox utilizando
# o esquema de URL https://download-installer.cdn.mozilla.net/pub/firefox/releases/latest/README.txt
# uso: sh beta
#
### VARIAVEIS

if [ -z "${ARCH}" ]; then
 case $(uname -m) in
  x86_64) ARCH=64;;  #Downloads for arch x86_64
   i?86|x86) ARCH=""; #Downloads for arch x86
    esac
     fi
### PRINCIPAL
# popular variaveis com valores padrao de sistema operacional e 
# linguagem, caso argumentos nao tenham sido passados 
if [ -z "${os}" ]; then
 case $(uname -s) in
  Linux)
   os=linux${ARCH}
    linguagem=${linguagem:-$(locale | grep "^LANG" |cut -f2 -d = | cut -f1 -d. | sed 's/_/-/g')}
     ;;
  *)
   os=win; #Downloads for arch x86
    linguagem=pt-BR
     esac
fi

#https://download.mozilla.org/?product=firefox-beta-latest&os=linux64&lang=en-US
echo "https://download.mozilla.org/?product=firefox-beta-latest&os=${os}&lang=${linguagem}"

DOWN=$(wget "https://download.mozilla.org/?product=firefox-beta-latest&os=linux64&lang=pt-BR" | grep -v "Localização: ")

if [ $os == linux${ARCH} ]; then

#firefox https://download.mozilla.org/?product=firefox-beta-latest\&os=${os}\&lang=${linguagem}
wget --content-disposition "https://download.mozilla.org/?product=firefox-beta-latest&os=${os}&lang=${linguagem}"
#wget -O firefox_${os}_${linguagem}.tar.bz2 "https://download.mozilla.org/?product=firefox-beta-latest&os=${os}&lang=${linguagem}"

else

#firefox https://download.mozilla.org/?product=firefox-beta-latest&os=${os}&lang=${linguagem}
wget --content-disposition "https://download.mozilla.org/?product=firefox-beta-latest&os=${os}&lang=${linguagem}"
#wget -O Firefox_${os}_${linguagem}.exe "https://download.mozilla.org/?product=firefox-beta-latest&os=${os}&lang=${linguagem}"

fi

#https://download-installer.cdn.mozilla.net/pub/firefox/releases/60.0b6/linux-x86_64/en-US/firefox-60.0b6.tar.bz2
#https://download-installer.cdn.mozilla.net/pub/firefox/releases/60.0b6/linux-i686/en-US/firefox-60.0b6.tar.bz2