#!/bin/sh
#http://ftp.slackware.com/pub/slackware/slackware64-current/slackware64/a/kernel-generic-4.14.11-x86_64-1.txz
#http://ftp.slackware.com/pub/slackware/slackware64-current/slackware64/a/kernel-huge-4.14.11-x86_64-2.txz
#http://ftp.slackware.com/pub/slackware/slackware64-current/slackware64/a/kernel-modules-4.14.11-x86_64-1.txz
#https://github.com/aaronsw
   
FTP_URL=${FTP_URL:-http://ftp.slackware.com}

# Section verify Archteture Systems (U|Li)n(i|u)x begins
if [ -z "${ARCH}" ]; then

   case "$(uname -m)" in
        x86_64) ARCH=64;;  #Downloads para arquitetura x86_64
        i?86|x86) ARCH="";; #Downloads para arquitetura x86
   esac

fi
# Section verify Archteture Systems (U|Li)n(i|u)x ends

LIB=${LIB:-lib}

BOOT=${BOOT:-boot}

FSTAB=${FSTAB:-/etc/fstab}

LILO=${LILO:-/etc/lilo.conf}

SLILO=${SLILO:-/sbin/lilo}

DEVDISK=${DEVDISK:-$(cat ${FSTAB} |tr '\t' ' ' |grep -v '^ *#' |tr -s ' ' |grep ' / ' |cut -f1 -d' ')}

PART=${PART:-$(mount | grep ${DEVDISK} | cut -c6-9)}

SYSARQ=${SYSARQ:-$(file -s ${DEVDISK} | awk '{print $5}')}

KRNL_URL=${KRNL_URL:-${FTP_URL}/pub/slackware/slackware${ARCH}-current/slackware${ARCH}/a/}

HUGE_PKG=${HUGE_PKG:-$(lynx --dump ${KRNL_URL} | egrep -o 'kernel-huge+-[0-9]+(.*).t?z$')}

GENERIC_PKG=${GENERIC_PKG:-$(lynx --dump ${KRNL_URL} | egrep -o 'kernel-generic+-[0-9]+(.*).t?z$')}

MODULES_PKG=${MODULES_PKG:-$(lynx --dump ${KRNL_URL} | egrep -o 'kernel-modules+-[0-9]+(.*).t?z$')}


# Variavel que pega a versão dp pacotes

VERSION=${VERSION:-$(echo ${HUGE_PKG} | rev | cut -f 3 -d - | rev )}


# Variaveis que pegam os tipos dos pacotes

HUGE_TYPE=${HUGE_TYPE:-$(echo ${HUGE_PKG} | rev | cut -f 4 -d - | rev )}

GENERIC_TYPE=${GENERIC_TYPE:-$(echo ${GENERIC_PKG} | rev | cut -f 4 -d - | rev )}

MODULES_TYPE=${MODULES_TYPE:-$(echo ${MODULES_PKG} | rev | cut -f 4 -d - | rev )}


# Variaveis para instalação e linkagem do kernel

VMHUGE=${VMHUGE:-vmlinuz-${HUGE_TYPE}-${VERSION}}

VMGENE=${VMGENE:-vmlinuz-${GENERIC_TYPE}-${VERSION}}

CONFHUGE=${CONFHUGE:-config-${HUGE_TYPE}-${VERSION}}

CONFGENE=${CONFGENE:-config-${GENERIC_TYPE}-${VERSION}}

SYSMAPHUGE=${SYSMAPHUGE:-System.map-${HUGE_TYPE}-${VERSION}}

SYSMAPGENE=${SYSMAPGENE:-System.map-${GENERIC_TYPE}-${VERSION}}

HUGE_LNK=${HUGE_LNK:-kernel_${HUGE_TYPE}-${VERSION}}

GENERIC_LNK=${GENERIC_LNK:-kernel_${GENERIC_TYPE}-${VERSION}}

HUGE_MAP=${HUGE_MAP:-sysmap_${HUGE_TYPE}-${VERSION}}

GENERIC_MAP=${GENERIC_MAP:-sysmap_${GENERIC_TYPE}-${VERSION}}


# Variaveis para downloads dos pacotes

URL_HUGE=${URL_HUGE:-${KRNL_URL}${HUGE_PKG}}

URL_GENERIC=${URL_GENERIC:-${KRNL_URL}${GENERIC_PKG}}

URL_MODULES=${URL_MODULES:-${KRNL_URL}${MODULES_PKG}}

#wget -c ${URL_HUGE}
#wget -c ${URL_GENERIC}
#wget -c ${URL_MODULES}

#tar -xf ${HUGE_PKG} ${BOOT}/{System.map,config,vmlinuz}-${HUGE_TYPE}-${VERSION}

#tar -xf ${GENERIC_PKG} ${BOOT}/{System.map,config,vmlinuz}-${GENERIC_TYPE}-${VERSION}

#tar -xf ${MODULES_PKG} ${LIB}/${MODULES_TYPE}/${VERSION}

#cp -ar ${LIB}/${MODULES_TYPE}/${VERSION} ${LIB}/${MODULES_TYPE}

#cp -ar ${BOOT}/{System.map,config,vmlinuz}-${HUGE_TYPE}-${VERSION} /${BOOT}

#cp -ar ${BOOT}/{System.map,config,vmlinuz}-${GENERIC_TYPE}-${VERSION} /${BOOT}

#ln -s /${BOOT}/${VMHUGE}     /${BOOT}/${HUGE_LNK}
#ln -s /${BOOT}/${VMGENE}     /${BOOT}/${GENERIC_LNK}
#ln -s /${BOOT}/${SYSMAPHUGE} /${BOOT}/${HUGE_MAP}
#ln -s /${BOOT}/${SYSMAPGENE} /${BOOT}/${GENERIC_MAP}



#echo "# Linux ${VERSION} bootable partition config begins
#image  = /${BOOT}/${HUGE_LNK}
#root   = /dev/'${PART}'
#label  = NEWKERNEL
#read-only
# Linux ${VERSION} bootable partition config ends " >> ${LILO}

#${SLILO}

rm -rf ${BOOT} ${LIB}