#!/bin/sh

VMHUGE=${VMHUGE:-vmlinuz-huge-$VERSION}

VMGENE=${VMGENE:-vmlinuz-generic-$VERSION}

CONFHUGE=${CONFHUGE:-config-huge-$VERSION}

CONFGENE=${CONFGENE:-config-generic-$VERSION}

SYSMAPHUGE=${SYSMAPHUGE:-System.map-huge-$VERSION}

SYSMAPGENE=${SYSMAPGENE:-System.map-generic-$VERSION}

GBUILD=${GBUILD:-$(echo kernel-generic-* | rev | cut -f 1 -d - | rev)}

UGBUILD=${UGBUILD:-$(echo kernel-huge-* | rev | cut -f 1 -d - | rev)}

MBUILD=${MBUILD:-$(echo kernel-modules-* | rev | cut -f 1 -d - | rev)}

VERSION=${VERSION:-$(echo kernel-generic-* | rev | cut -f 3 -d - | rev )}

ARCHKERNEL=${ARCHKERNEL:-$(echo kernel-generic-* | rev | cut -f 2 -d - | rev)}

      
tar -xf AB/kernel-huge-$VERSION-$ARCHKERNEL-$UGBUILD boot/{System.map,config,vmlinuz}-huge-$VERSION

tar -xf AB/kernel-generic-$VERSION-$ARCHKERNEL-$GBUILD boot/{System.map,config,vmlinuz}-generic-$VERSION

tar -xf AB/kernel-modules-$VERSION-$ARCHKERNEL-$MBUILD lib/modules/$VERSION

#cp -ar lib/modules/$VERSION /lib/modules

#cp -ar boot/{System.map,config,vmlinuz}-huge-$VERSION  /boot

#cp -ar boot/{System.map,config,vmlinuz}-generic-$VERSION /boot

#ln -s /boot/$VMHUGE     /boot/kernel_huge-$VERSION
#ln -s /boot/$VMGENE     /boot/kernel_gene-$VERSION
#ln -s /boot/$SYSMAPHUGE /boot/sysmap_huge-$VERSION
#ln -s /boot/$SYSMAPGENE /boot/sysmap_gene-$VERSION

#echo "# Linux $VERSION bootable partition config begins
#image  = /boot/kernel_huge-$VERSION
#root   = /dev/sda1
#label  = NEWKERNEL
#read-only
# Linux $VERSION bootable partition config ends " >> /etc/lilo.conf

#lilo