#!/bin/sh
#######################################################################################################
#                                                                                                      
# Autor: Jean Zonta                                                                                    
# Pseudonym: wiki.anon                                                                                 
# Script Name: ksl                                                                                     
# License: GNU/GPL V3                                                                                  
# DateTime: dom 18 mar 2018 15:42:00                                                                   
# echo "}oqo4gtutF_gnuu4ius4hx" | perl -pe \ 's/(.)/chr(ord($1)-2*3)/ge'                               
# echo 'comhttps://slackwarewww' | sed 's@\(com\)\(https://\)\(slackware\)\(www\)@\2\4.\3.\1 ..!!!@'   
#                                                                                                      
#######################################################################################################
if [ $(id -u) -ne 0 ]; then
 echo -e "\n\e[1;34m User \e[1;31m${USER}\e[0m \e[1;34mis not root\n make login as root\n to run the script\e[0m ..!!\n"
  exit
   else
# Section verify Archteture Systems (U|Li)n(i|u)x begins
if [ -z "${ARCH}" ]; then
 case $(uname -m) in
  x86_64) ARCH=64;;  #Downloads for arch x86_64
   i?86|x86) ARCH=""; #Downloads for arch x86
    esac
     fi     
# Section verify Archteture Systems (U|Li)n(i|u)x ends

LIB=${LIB:-lib}

BOOT=${BOOT:-boot}

FSTAB=${FSTAB:-/etc/fstab}

SLILO=${SLILO:-/sbin/lilo}

LILO=${LILO:-/etc/lilo.conf}

LIBMODULES=${LIBMODULES:-/${LIB}/modules}

# Where do we look for sources?
SRCDIR=${SRCDIR:-$(pwd)}

DEVDISK=${DEVDISK:-$(cat ${FSTAB} | tr '\t' ' ' | grep -v '^ *#' | tr -s ' ' | grep ' / ' | cut -f1 -d' ')}

PART=${PART:-$(mount | grep ${DEVDISK} | awk '{print $1}' | cut -f3 -d/)}

SYSARQ=${SYSARQ:-$(file -s ${DEVDISK} | awk '{print $5}')}

FTP_URL=${FTP_URL:-http://ftp.slackware.com}

KRNL_URL=${KRNL_URL:-${FTP_URL}/pub/slackware/slackware${ARCH}-current/slackware${ARCH}/a/}

HUGE_PKG=${HUGE_PKG:-$(lynx --dump ${KRNL_URL} | egrep -o 'kernel-huge+-[0-9]+(.*).t?z$')}

GENERIC_PKG=${GENERIC_PKG:-$(lynx --dump ${KRNL_URL} | egrep -o 'kernel-generic+-[0-9]+(.*).t?z$')}

MODULES_PKG=${MODULES_PKG:-$(lynx --dump ${KRNL_URL} | egrep -o 'kernel-modules+-[0-9]+(.*).t?z$')}


# Variavel que pega a versão dp pacotes

VERSION=${VERSION:-$(echo ${HUGE_PKG} | cut -f3 -d -)}

# Variaveis para instalação e linkagem do kernel

VMHUGE=${VMHUGE:-/${BOOT}/vmlinuz-${HUGE_PKG:7:4}-${HUGE_PKG:12:7}}

VMGENE=${VMGENE:-/${BOOT}/vmlinuz-${GENERIC_PKG:7:7}-${GENERIC_PKG:14:8}}

CONFHUGE=${CONFHUGE:-/${BOOT}/config-${HUGE_PKG:7:4}-${HUGE_PKG:12:7}}

CONFGENE=${CONFGENE:-/${BOOT}/config-${GENERIC_PKG:7:7}-${GENERIC_PKG:14:8}}

SYSMAPHUGE=${SYSMAPHUGE:-/${BOOT}/System.map-${HUGE_PKG:7:4}-${HUGE_PKG:12:7}}

SYSMAPGENE=${SYSMAPGENE:-/${BOOT}/System.map-${GENERIC_PKG:7:7}-${GENERIC_PKG:14:8}}

HUGE_LNK=${HUGE_LNK:-/${BOOT}/kernel_${HUGE_PKG:7:4}-${HUGE_PKG:12:7}}

GENERIC_LNK=${GENERIC_LNK:-/${BOOT}/kernel_${GENERIC_PKG:7:7}-${GENERIC_PKG:14:8}}

HUGE_MAP=${HUGE_MAP:-/${BOOT}/sysmap_${HUGE_PKG:7:4}-${HUGE_PKG:12:7}}

GENERIC_MAP=${GENERIC_MAP:-/${BOOT}/sysmap_${GENERIC_PKG:7:7}-${GENERIC_PKG:14:8}}


# variables for package downloads

URL_HUGE=${URL_HUGE:-${KRNL_URL}${HUGE_PKG}}

URL_GENERIC=${URL_GENERIC:-${KRNL_URL}${GENERIC_PKG}}

URL_MODULES=${URL_MODULES:-${KRNL_URL}${MODULES_PKG}}

SOURCE_HUGE=${SOURCE_HUGE:-${SRCDIR}/$(basename ${HUGE_PKG})}

SOURCE_GENERIC=${SOURCE_GENERIC:-${SRCDIR}/$(basename ${GENERIC_PKG})}

SOURCE_MODULE=${SOURCE_MODULE:-${SRCDIR}/$(basename ${MODULES_PKG})}

MKINITRD=${MKINITRD:-/sbin/mkinitrd}

INITRDGENERIC=${INITRDGENERIC:-/${BOOT}/initrd-${GENERIC_PKG:14:8}-${GENERIC_PKG:7:7}}

LINKINITRD=${LINKINITRD:-/${BOOT}/initrd-${GENERIC_PKG:14:8}}

MKINITRDCOMMAND=${MKINITRDCOMMAND:-/usr/share/mkinitrd/mkinitrd_command_generator.sh}

MKINITRDSTRINGS=${MKINITRDSTRINGS:-$(${MKINITRDCOMMAND} | grep ^mkinitrd | cut -f10 -d ' ')}

# Source file availability:

if [ -f ${SOURCE_HUGE} ]; then
  if [ $? -ne 0 -o ! -s ${SOURCE_HUGE} ]; then
   echo "Downloading $(basename ${SOURCE_HUGE}) failed... aborting the build."
    mv -f ${SOURCE_HUGE} ${SOURCE_HUGE}.FAIL
     exit
      else
       tar -xf ${SOURCE_HUGE} ${BOOT}/{System.map,config,vmlinuz}-${HUGE_PKG:7:4}-${HUGE_PKG:12:7}
        cp -ar ${SRCDIR}/${BOOT}/{System.map,config,vmlinuz}-${HUGE_PKG:7:4}-${HUGE_PKG:12:7} /${BOOT}
         fi
         
  if [ ! -f ${VMHUGE} ]; then
   echo "Not, found it ${VMHUGE} .!"
    exit
     else
      echo "Ah, found it ${VMHUGE} .!"
       ln -s ${VMHUGE} ${HUGE_LNK}
        fi
   
  if [ ! -f ${SYSMAPHUGE} ]; then
   echo "Not, found it ${SYSMAPHUGE} .!"
    exit
     else
      echo "Ah, found it ${SYSMAPHUGE} .!"
       ln -s ${SYSMAPHUGE} ${HUGE_MAP}
        fi
else

 echo "Source $(basename ${SOURCE_HUGE}) not available yet..."
  # Check if the $SRCDIR is writable at all - if not, download to $SOURCE
  [ -w ${SRCDIR} ] ||  ${SOURCE_HUGE}
  
   echo "Will download file to ${SOURCE_HUGE}"
    wget -nv -T 20 ${URL_HUGE} || true
     echo "Download complete."
      
  if [ $? -ne 0 -o ! -s ${SOURCE_HUGE} ]; then
   echo "Downloading $(basename ${SOURCE_HUGE}) failed... aborting the build."
    mv -f ${SOURCE_HUGE} ${SOURCE_HUGE}.FAIL
     exit 1
      else
       tar -xf ${SOURCE_HUGE} ${BOOT}/{System.map,config,vmlinuz}-${HUGE_PKG:7:4}-${HUGE_PKG:12:7}
        cp -ar ${SRCDIR}/${BOOT}/{System.map,config,vmlinuz}-${HUGE_PKG:7:4}-${HUGE_PKG:12:7} /${BOOT}
         fi
         
  if [ ! -f ${VMHUGE} ]; then
   echo "Not, found it ${VMHUGE} .!"
    exit 1
     else
      echo "Ah, found it ${VMHUGE} .!"
       ln -s ${VMHUGE} ${HUGE_LNK}
        fi
   
  if [ ! -f ${SYSMAPHUGE} ]; then
   echo "Not, found it ${SYSMAPHUGE} .!"
    exit
     else
      echo "Ah, found it ${SYSMAPHUGE} .!"
       ln -s ${SYSMAPHUGE} ${HUGE_MAP}
        fi
fi # end condition SOURCE_HUGE

if [ -f ${SOURCE_GENERIC} ]; then
  if [ $? -ne 0 -o ! -s ${SOURCE_GENERIC} ]; then
   echo "Downloading $(basename ${SOURCE_GENERIC}) failed... aborting the build."
    mv -f ${SOURCE_GENERIC} ${SOURCE_GENERIC}.FAIL
     exit
      else
       tar -xf ${SOURCE_GENERIC} ${BOOT}/{System.map,config,vmlinuz}-${GENERIC_PKG:7:7}-${GENERIC_PKG:14:8}
        cp -ar ${SRCDIR}/${BOOT}/{System.map,config,vmlinuz}-${GENERIC_PKG:7:7}-${GENERIC_PKG:14:8} /${BOOT}
         fi
         
  if [ ! -f ${SYSMAPGENE} ]; then
   echo "Not, found it ${SYSMAPGENE} .!"
    exit
     else
      echo "Ah, found it ${SYSMAPGENE} .!"
       ln -s ${SYSMAPGENE} ${GENERIC_MAP}
        fi
    
  if [ ! -f ${VMGENE} ]; then
   echo "Not, found it ${VMGENE} .!"
    exit
     else
      echo "Ah, found it ${VMGENE} .!"
       ln -s ${VMGENE} ${GENERIC_LNK}
        fi
    
  if [ ! -f ${GENERIC_LNK} ]; then
   echo "Not, found it ${GENERIC_LNK} .!"
    exit
     else
      echo "Ah, found it ${GENERIC_LNK} .!"
       fi
else

 echo "Source $(basename ${SOURCE_GENERIC}) not available yet..."
  # Check if the $SRCDIR is writable at all - if not, download to $SOURCE
  [ -w ${SRCDIR} ] ||  ${SOURCE_GENERIC}
  
   echo "Will download file to ${SOURCE_GENERIC}"
    wget -nv -T 20 ${URL_GENERIC} || true
     echo "Download complete."
      
  if [ $? -ne 0 -o ! -s ${SOURCE_GENERIC} ]; then
   echo "Downloading $(basename ${SOURCE_GENERIC}) failed... aborting the build."
    mv -f ${SOURCE_GENERIC} ${SOURCE_GENERIC}.FAIL
     exit
      else
       tar -xf ${SOURCE_GENERIC} ${BOOT}/{System.map,config,vmlinuz}-${GENERIC_PKG:7:7}-${GENERIC_PKG:14:8}
        cp -ar ${SRCDIR}/${BOOT}/{System.map,config,vmlinuz}-${GENERIC_PKG:7:7}-${GENERIC_PKG:14:8} /${BOOT}
         fi
         
  if [ ! -f ${SYSMAPGENE} ]; then
   echo "Not, found it ${SYSMAPGENE} .!"
    exit
     else
      echo "Ah, found it ${SYSMAPGENE} .!"
       ln -s ${SYSMAPGENE} ${GENERIC_MAP}
        fi
    
  if [ ! -f ${VMGENE} ]; then
   echo "Not, found it ${VMGENE} .!"
    exit
     else
      echo "Ah, found it ${VMGENE} .!"
       ln -s ${VMGENE} ${GENERIC_LNK}
        fi
    
  if [ ! -f ${GENERIC_LNK} ]; then
   echo "Not, found it ${GENERIC_LNK} .!"
    exit
     else
      echo "Ah, found it ${GENERIC_LNK} .!"
       fi
fi # end condition SOURCE_GENERIC

if [ -f ${SOURCE_MODULE} ]; then

  if [ $? -ne 0 -o ! -s ${SOURCE_MODULE} ]; then
   echo "Downloading $(basename ${SOURCE_MODULE}) failed... aborting the build."
    mv -f ${SOURCE_MODULE} ${SOURCE_MODULE}.FAIL
     exit
      else
       tar -xf ${SOURCE_MODULE} ${LIB}/${MODULES_PKG:7:7}/${MODULES_PKG:15:7}
        cp -ar ${SRCDIR}/${LIB}/${MODULES_PKG:7:7}/${MODULES_PKG:15:7} ${LIBMODULES}
         fi
         
  if [ ! -d ${LIBMODULES}/${MODULES_PKG:15:7} ]; then
   echo "Not, found it ${LIBMODULES}/${MODULES_PKG:15:7} .!"
    exit
     else
      echo "Ah, found it ${LIBMODULES}/${HUGE_PKG:12:7} .!"
       fi
else

  echo "Source '$(basename ${SOURCE_MODULE})' not available yet..."
  # Check if the $SRCDIR is writable at all - if not, download to $SOURCE
  [ -w "${SRCDIR}" ] ||  ${SOURCE_MODULE}
  
   echo "Will download file to ${SOURCE_MODULE}"
    wget -nv -T 20 ${URL_MODULES} || true
     echo "Download complete."
      
  if [ $? -ne 0 -o ! -s ${SOURCE_MODULE} ]; then
   echo "Downloading $(basename ${SOURCE_MODULE}) failed... aborting the build."
    mv -f ${SOURCE_MODULE} ${SOURCE_MODULE}.FAIL
     exit
      else
       tar -xf ${SOURCE_MODULE} ${LIB}/${MODULES_PKG:7:7}/${MODULES_PKG:15:7}
        cp -ar ${SRCDIR}/${LIB}/${MODULES_PKG:7:7}/${MODULES_PKG:15:7} ${LIBMODULES}
         fi
         
  if [ ! -d ${LIBMODULES}/${MODULES_PKG:15:7} ]; then
   echo "Not, found it ${LIBMODULES}/${MODULES_PKG:15:7} .!"
    exit
     else
      echo "Ah, found it ${LIBMODULES}/${MODULES_PKG:15:7} .!"
       fi
fi # end condition SOURCE_MODULE

echo "Which kernel do you want to install?"
read -p "Enter type g(eneric) ou h(uge): " resposta

if [[ ${resposta} == "g" || ${resposta} == "G"  ]]; then

${MKINITRD} -c -k ${MODULES_PKG:15:7} -f ${SYSARQ} -r ${DEVDISK} -m ${MKINITRDSTRINGS} -u -o ${INITRDGENERIC}

ln -s ${INITRDGENERIC} ${LINKINITRD}

read -p "Do you want to add a(fter) or at the e(nd) of lilo.conf? " resposta

if [[ ${resposta} == "a" || ${resposta} == "A" ]]; then

## Adiciona partição após "# End LILO global section" no lilo.conf
sed -i "63s/$/\n# Linux ${GENERIC_PKG:14:8} bootable generic partition config begins/g;
        63s/$/\nimage  = \/boot\/kernel_${GENERIC_PKG:7:7}-${GENERIC_PKG:14:8}/g;
        63s/$/\ninitrd = \/${BOOT}\/initrd-${GENERIC_PKG:14:8}/g;
        63s/$/\nroot   = \/dev\/${PART}/g;
        63s/$/\nlabel  = GNRC-${GENERIC_PKG:14:8}/g;
        63s/$/\nread-only/g;
        63s/$/\n# Linux ${GENERIC_PKG:14:8} bootable generic partition config ends/g;
       " ${LILO}

echo -e "\nKernel GNRC-${GENERIC_PKG:14:8} install sucessfull.\n"

else
## Adiciona partição no fim de lilo.conf
echo "# Linux ${GENERIC_PKG:14:8} bootable generic partition config begins
image  = /${BOOT}/kernel_${GENERIC_PKG:7:7}-${GENERIC_PKG:14:8}
initrd = /${BOOT}/initrd-${GENERIC_PKG:14:8}
root   = /dev/${PART}
label  = GNRC-${GENERIC_PKG:14:8}
read-only
# Linux ${GENERIC_PKG:14:8} bootable generic partition config ends" >> ${LILO}

echo -e "\nKernel GNRC-${GENERIC_PKG:14:8} install sucessfull.\n"

fi # fim condition resposta

else

echo "# Linux ${HUGE_PKG:12:7} bootable partition config begins
image  = /${BOOT}/kernel_${HUGE_PKG:7:4}-${HUGE_PKG:12:7}
root   = /dev/${PART}
label  = HG-${HUGE_PKG:12:7}
read-only
# Linux ${HUGE_PKG:12:7} bootable partition config ends" >> ${LILO}

echo -e "\nKernel HG-${HUGE_PKG:12:7} install sucessfull.\n"

fi # fim condition resposta generic

${SLILO} # exec /sbin/lilo

# remove dirs and packages
rm -rf ${SRCDIR}/${BOOT}
rm -rf ${SRCDIR}/${LIB}
rm -rf ${SOURCE_HUGE}
rm -rf ${SOURCE_GENERIC}
rm -rf ${SOURCE_MODULE}

fi # end condition Check admin