#!/bin/sh
#https://www.postgresql.org/ftp/source/v10.2/
#https://ftp.postgresql.org/pub/source/v10.2/postgresql-10.2.tar.gz
#https://ftp.postgresql.org/pub/latest/postgresql-10.2.tar.gz
CWD=$(pwd)

PRGNAM=${PRGNAM:-postgresql}

URL_PG=${URL_PG:-https://ftp.postgresql.org/pub/source/}

HREF_PATTERN=${HREF_PATTERN:-'s/.*href="\([^"]*\).*/\1/p'}

# SVERSION=v10.3/
SVERSION=${SVERSION:-$(curl -s ${URL_PG} | sed -n ${HREF_PATTERN} | grep "v" | sort -V | tail -n 1)}

# URL_DB=https://ftp.postgresql.org/pub/source/v10.3/
URL_DB=${URL_DB:-${URL_PG}${SVERSION}}

# VER_DB=10.3
VER_DB=${VER_DB:-$(echo ${SVERSION} | sed 's/[a-z]//g;s/\///g;')}

# PKGNAME_DB=postgresql-10.3.tar.gz
PKGNAME_DB=${PKGNAME_DB:-$(lynx --dump ${URL_DB} | awk -F'/' '/postgresql+-[0-9]+.*\.tar\.gz$/ {print $7}' | head -n1)}

# URL_PKG=https://ftp.postgresql.org/pub/source/v10.3/postgresql-10.3.tar.gz
URL_PKG=${URL_PKG:-${URL_DB}${PKGNAME_DB}}

EXTENSION_PKG=${EXTENSION_PKG:-$(echo ${PKGNAME_DB} | cut -f3,4 -d.)}

SOURCE=${SOURCE:-${CWD}/${PRGNAM}-${VER_DB}.${EXTENSION_PKG}}


if [ -f ${SOURCE} ]; then 

echo "Ah, found it ${SOURCE} .!";

# Source file availability:
elif [ ! -f ${SOURCE} ]; then
  echo "Source '$(basename ${SOURCE})' not available yet..."
  # Check if the $SRCDIR is writable at all - if not, download to $SOURCE
  [ -w "${CWD}" ] ||  ${SOURCE}
  
  if ! [ "x${URL_PKG}" == "x" ]; then
   echo "Will download file to $(dirname $SOURCE)"
    wget -nv -T 20 "${URL_PKG}" || true
     echo "Download complete."
    
    if [ $? -ne 0 -o ! -s "${SOURCE}" ]; then
     echo "Downloading '${SOURCE}' failed... aborting the build."
      mv -f "${SOURCE}" "${SOURCE}".FAIL
       exit 1
    fi
  else
    echo "File '$(basename ${SOURCE})' not available... aborting the build."
     exit 1
  fi
fi