#!/bin/sh

if [ ! -f $(ls *.rar) ]; then
 echo "Nenhum arquivo .rar encontrado"
  else

#Thundercats-EP001.rar
unrar e Thundercats-EP001.rar

#Thundercats-EP002.rar
unrar e Thundercats-EP002.rar

#Thundercats-EP003.rar
unrar e Thundercats-EP003.rar

#Thundercats-EP004.rar
unrar e Thundercats-EP004.rar

#Thundercats-EP005.rar
unrar e Thundercats-EP005.rar

#Thundercats-EP006.rar
unrar e Thundercats-EP006.rar

#Thundercats-EP007.rar
unrar e Thundercats-EP007.rar

#Thundercats-EP008.rar
unrar e Thundercats-EP008.rar

#Thundercats-EP009.rar
unrar e Thundercats-EP009.rar

#Thundercats-EP010.rar
unrar e Thundercats-EP010.rar

#Thundercats-EP011.rar
unrar e Thundercats-EP011.rar

#Thundercats-EP012.rar
unrar e Thundercats-EP012.rar

#Thundercats-EP013.rar
unrar e Thundercats-EP013.rar

#Thundercats-EP014.rar
unrar e Thundercats-EP014.rar

#Thundercats-EP015.rar
unrar e Thundercats-EP015.rar

#Thundercats-EP016.rar
unrar e Thundercats-EP016.rar

#Thundercats-EP017.rar
unrar e Thundercats-EP017.rar

#Thundercats-EP018.rar
unrar e Thundercats-EP018.rar

#Thundercats-EP019.rar
unrar e Thundercats-EP019.rar

#Thundercats-EP020.rar
unrar e Thundercats-EP020.rar

#Thundercats-EP021.rar
unrar e Thundercats-EP021.rar

#Thundercats-EP022.rar
unrar e Thundercats-EP022.rar

#Thundercats-EP023.rar
unrar e Thundercats-EP023.rar

#Thundercats-EP024.rar
unrar e Thundercats-EP024.rar

#Thundercats-EP025.rar
unrar e Thundercats-EP025.rar

#Thundercats-EP026.rar
unrar e Thundercats-EP026.rar

#Thundercats-EP027.rar
unrar e Thundercats-EP027.rar

#Thundercats-EP028.rar
unrar e Thundercats-EP028.rar

#Thundercats-EP029.rar
unrar e Thundercats-EP029.rar

#Thundercats-EP030.rar
unrar e Thundercats-EP030.rar

#Thundercats-EP031.rar
unrar e Thundercats-EP031.rar

#Thundercats-EP032.rar
unrar e Thundercats-EP032.rar

#Thundercats-EP033.rar
unrar e Thundercats-EP033.rar

#Thundercats-EP034.rar
unrar e Thundercats-EP034.rar

#Thundercats-EP035.rar
unrar e Thundercats-EP035.rar

#Thundercats-EP036.rar
unrar e Thundercats-EP036.rar

#Thundercats-EP037.rar
unrar e Thundercats-EP037.rar

#Thundercats-EP038.rar
unrar e Thundercats-EP038.rar

#Thundercats-EP039.rar
unrar e Thundercats-EP039.rar

#Thundercats-EP040.rar
unrar e Thundercats-EP040.rar

#Thundercats-EP041.rar
unrar e Thundercats-EP041.rar

#Thundercats-EP042.rar
unrar e Thundercats-EP042.rar

#Thundercats-EP043.rar
unrar e Thundercats-EP043.rar

#Thundercats-EP044.rar
unrar e Thundercats-EP044.rar

#Thundercats-EP045.rar
unrar e Thundercats-EP045.rar

#Thundercats-EP046.rar
unrar e Thundercats-EP046.rar

#Thundercats-EP047.rar
unrar e Thundercats-EP047.rar

#Thundercats-EP048.rar
unrar e Thundercats-EP048.rar

#Thundercats-EP049.rar
unrar e Thundercats-EP049.rar

#Thundercats-EP050.rar
unrar e Thundercats-EP050.rar

#Thundercats-EP051.rar
unrar e Thundercats-EP051.rar

#Thundercats-EP052.rar
unrar e Thundercats-EP052.rar

#Thundercats-EP053.rar
unrar e Thundercats-EP053.rar

#Thundercats-EP054.rar
unrar e Thundercats-EP054.rar

#Thundercats-EP055.rar
unrar e Thundercats-EP055.rar

#Thundercats-EP056.rar
unrar e Thundercats-EP056.rar

#Thundercats-EP057.rar
unrar e Thundercats-EP057.rar

#Thundercats-EP058.rar
unrar e Thundercats-EP058.rar

#Thundercats-EP059.rar
unrar e Thundercats-EP059.rar

#Thundercats-EP060.rar
unrar e Thundercats-EP060.rar

#Thundercats-EP061.rar
unrar e Thundercats-EP061.rar

#Thundercats-EP062.rar
unrar e Thundercats-EP062.rar

#Thundercats-EP063.rar
unrar e Thundercats-EP063.rar

#Thundercats-EP064.rar
unrar e Thundercats-EP064.rar

#Thundercats-EP065.rar
unrar e Thundercats-EP065.rar

#Thundercats-EP066.rar
unrar e Thundercats-EP066.rar

#Thundercats-EP067.rar
unrar e Thundercats-EP067.rar

#Thundercats-EP068.rar
unrar e Thundercats-EP068.rar

#Thundercats-EP069.rar
unrar e Thundercats-EP069.rar

#Thundercats-EP070.rar
unrar e Thundercats-EP070.rar

#Thundercats-EP071.rar
unrar e Thundercats-EP071.rar

#Thundercats-EP072.rar
unrar e Thundercats-EP072.rar

#Thundercats-EP073.rar
unrar e Thundercats-EP073.rar

#Thundercats-EP074.rar
unrar e Thundercats-EP074.rar

#Thundercats-EP075.rar
unrar e Thundercats-EP075.rar

#Thundercats-EP076.rar
unrar e Thundercats-EP076.rar

#Thundercats-EP077.rar
unrar e Thundercats-EP077.rar

#Thundercats-EP078.rar
unrar e Thundercats-EP078.rar

#Thundercats-EP079.rar
unrar e Thundercats-EP079.rar

#Thundercats-EP080.rar
unrar e Thundercats-EP080.rar

#Thundercats-EP081.rar
unrar e Thundercats-EP081.rar

#Thundercats-EP082.rar
unrar e Thundercats-EP082.rar

#Thundercats-EP083.rar
unrar e Thundercats-EP083.rar

#Thundercats-EP084.rar
unrar e Thundercats-EP084.rar

#Thundercats-EP085.rar
unrar e Thundercats-EP085.rar

#Thundercats-EP086.rar
unrar e Thundercats-EP086.rar

#Thundercats-EP087.rar
unrar e Thundercats-EP087.rar

#Thundercats-EP088.rar
unrar e Thundercats-EP088.rar

#Thundercats-EP089.rar
unrar e Thundercats-EP089.rar

#Thundercats-EP090.rar
unrar e Thundercats-EP090.rar

#Thundercats-EP091.rar
unrar e Thundercats-EP091.rar

#Thundercats-EP092.rar
unrar e Thundercats-EP092.rar

#Thundercats-EP093.rar
unrar e Thundercats-EP093.rar

#Thundercats-EP094.rar
unrar e Thundercats-EP094.rar

#Thundercats-EP095.rar
unrar e Thundercats-EP095.rar

#Thundercats-EP096.rar
unrar e Thundercats-EP096.rar

#Thundercats-EP097.rar
unrar e Thundercats-EP097.rar

#Thundercats-EP098.rar
unrar e Thundercats-EP098.rar

#Thundercats-EP099.rar
unrar e Thundercats-EP099.rar

#Thundercats-EP100.rar
unrar e Thundercats-EP100.rar

#Thundercats-EP101.rar
unrar e Thundercats-EP101.rar

#Thundercats-EP102.rar
unrar e Thundercats-EP102.rar

#Thundercats-EP103.rar
unrar e Thundercats-EP103.rar

#Thundercats-EP104.rar
unrar e Thundercats-EP104.rar

#Thundercats-EP105.rar
unrar e Thundercats-EP105.rar

#Thundercats-EP106.rar
unrar e Thundercats-EP106.rar

#Thundercats-EP107.rar
unrar e Thundercats-EP107.rar

#Thundercats-EP108.rar
unrar e Thundercats-EP108.rar

#Thundercats-EP109.rar
unrar e Thundercats-EP109.rar

#Thundercats-EP110.rar
unrar e Thundercats-EP110.rar

#Thundercats-EP111.rar
unrar e Thundercats-EP111.rar

#Thundercats-EP112.rar
unrar e Thundercats-EP112.rar

#Thundercats-EP113.rar
unrar e Thundercats-EP113.rar

#Thundercats-EP114.rar
unrar e Thundercats-EP114.rar

#Thundercats-EP115.rar
unrar e Thundercats-EP115.rar

#Thundercats-EP116.rar
unrar e Thundercats-EP116.rar

#Thundercats-EP117.rar
unrar e Thundercats-EP117.rar

#Thundercats-EP118.rar
unrar e Thundercats-EP118.rar

#Thundercats-EP119.rar
unrar e Thundercats-EP119.rar

#Thundercats-EP120.rar
unrar e Thundercats-EP120.rar

#Thundercats-EP121.rar
unrar e Thundercats-EP121.rar

#Thundercats-EP122.rar
unrar e Thundercats-EP122.rar

#Thundercats-EP123.rar
unrar e Thundercats-EP123.rar

#Thundercats-EP124.rar
unrar e Thundercats-EP124.rar

#Thundercats-EP125.rar
unrar e Thundercats-EP125.rar

#Thundercats-EP126.rar
unrar e Thundercats-EP126.rar

#Thundercats-EP127.rar
unrar e Thundercats-EP127.rar

#Thundercats-EP128.rar
unrar e Thundercats-EP128.rar

#Thundercats-EP129.rar
unrar e Thundercats-EP129.rar

#Thundercats-EP130.rar
unrar e Thundercats-EP130.rar

fi

if [ ! -d $(pwd)/compactados ]; then
 mkdir compactados
  mv *.rar compactados/
   else
    mv *.rar compactados/
     fi
     