#!/bin/bash

QTD=$(find $1 -iname "*.rar" | wc -l)

i="1"

while [ ${i} -le ${QTD} ];
 do
  ARQUIVOCOMPLETO=$(ls *.rar | head -${i} | tail -1)
  unrar x -y "${ARQUIVOCOMPLETO}"
 i=$((${i}+1))
done

#<<<---->>>------------------------------------------------------------------------------------------

QTD=$(find $1 -iname "*.zip" | wc -l)
j="1"

while [ ${j} -le ${QTD} ];
 do
  ARQUIVOCOMPLETO=${ARQUIVOCOMPLETO:-$(ls *.zip | head -${j} | tail -1)}
  unzip "${ARQUIVOCOMPLETO}"
 j=$((${j}+1))
done

#<<<---->>>------------------------------------------------------------------------------------------

QTD=$(ls -d */ | wc -l)
k="1"

while [ ${k} -le ${QTD} ];
do
 ARQUIVOCOMPLETO=$(ls -d */ | head -${k} | tail -1)
 
  NOVONOME=${NOVONOME:-$(echo ${ARQUIVOCOMPLETO} | sed 's/^ //g;s/ - /_/g;s/ /_/g;s/ $//g;')}
  mv "${ARQUIVOCOMPLETO}" ${NOVONOME}
 k=$((${k}+1))
done

#<<<---->>>------------------------------------------------------------------------------------------

COMPACTADOS=${COMPACTADOS:-$(ls | egrep '\.rar$|\.zip$')}
DESCOMPACTADOS=${DESCOMPACTADOS:-$(ls | egrep '\.avi$|\.flv$|\.mp4$|\.rmvb$|\.mkv$')}

if [[ ! -d $(pwd)/compactados && ! -d $(pwd)/descompactados ]]; then 
 mkdir compactados
  mkdir descompactados
   mv ${COMPACTADOS} compactados/
    mv ${DESCOMPACTADOS} descompactados/
else
 mv ${COMPACTADOS} compactados/
  mv ${DESCOMPACTADOS} descompactados/
   fi
   
exit 0